### PR TITLE
Enhance/weapon viewmodels

### PR DESCRIPTION
**Pull request by VortexParadox**
This brings the HL2 arms to all common weapons used in the game, such as the Rocket Launcher (with its own centered version), Sticky Launcher, Pistol and Knife. The Pistol and Knife being entirely new models.
All weapons use the new PBR shader, including Gordon's hands.

The SMG, L12G, Grenade and Sniper were left behind as some seem no longer attached with the game's art direction, and I see it's better to improve on them first, specially as there is a possibility to get a c_models environment soon(tm). Weapon models and materials folders have been already restructured to prepare for it in any case.

https://youtu.be/CsXiZ0yGUOc

### Checklist
- [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [x]  If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x]  If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x]  If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [x]  If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [x] My commits are relatively small and scoped to the best of my ability
- [x]  My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x]  My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

**Comment by braem** [comment]
Really loving the new rocket launcher, especially centered :D . Everything looks great from what I can tell, though the video looks like you're on a higher viewmodel FOV than default 54. On 54 you dont get to see the chamber rotation of the rocket launcher:
image
Not sure if that really matters though.

Only other thing I noticed is the stickies are quite a lot darker (thanks to PBR im guessing) though pretty visible still thanks to the circle particle.
Develop:
image

This branch:
image

**Comment by VortexParadox** [comment]
Different FOVs will occlude certain areas of the weapons. I had to balance the animations to fit the middle ground of 60°. I wished we could settle on a higher viewmodel FOV, as 54 default is too close and takes a lot of screen space
Regarding the stickybomb, there's another thing I could try to improve visibility, including just changing the material or having a static cubemap.
image

**Comment by braem** [comment]
Related: https://github.com/momentum-mod/game/issues/892

**Comment by Gocnak** [comment]
We can raise the default view model FOV to a default that is more reasonable. 70 was supposedly a good compromise, but 60 also works. Feel free to do that here in this branch.

**Review by Gocnak — APPROVED** [review]

**Pull request merged**
