### PR TITLE
Add docs/ directory, consolidate build guides

### LINKED ISSUE #64: Update linux build steps with netbeans stuff
https://github.com/momentum-mod/game/pull/894/

~Also update MomentumDev zip link with new link: https://drive.google.com/file/d/1HD1Mh8JrCBqP2sh8WJCpfybJGI4BPcZ4/view?usp=sharing~ This is now included in the site.

### PR DESCRIPTION
**Pull request by geight**
Closes https://github.com/momentum-mod/docs/issues/64

This PR:
* Moves the original build guide from the `docs` repo to a `docs/` directory in this repo
* Adds a guide for building `0.8.7` with NetBeans (for Linux) so that anyone building that version has documentation to reference if necessary
* Consolidates both guides into a single documentation source (with a few formatting enhancements here and there)

### Checklist
- [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [x] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

**Comment by Gocnak** [comment]
I think it'd be great to move the entire "building the game" guide here and link to it instead of our docs site! And to consolidate all of it into the one guide would be best.

**Comment by geight** [comment]
> I think it'd be great to move the entire "building the game" guide here and link to it instead of our docs site! And to consolidate all of it into the one guide would be best.

Sounds good. I'll put this into a draft and get that moved over (and log a PR to clean up the resources in `docs/`).

**Comment by geight** [comment]
The guide can be previewed [here](https://github.com/geight/game/blob/geight-netbeans-build/docs/build-guide.md) where the relative image paths work for the time being.

**Review by braem — DISMISSED** [review]

**Review by Gocnak — CHANGES_REQUESTED** [review]
One last nit, the images should be in the docs subfolder! So `docs/images/...`

But other than that looks great!

**Comment by geight** [comment]
> One last nit, the images should be in the docs subfolder! So `docs/images/...`
> 
> But other than that looks great!

Updated here [`e83db4e` (#1614)](https://github.com/momentum-mod/game/pull/1614/commits/e83db4eb4485ad2e2ff6c44e0957e80555c9dbd0) 🚀

**Review by Gocnak — APPROVED** [review]

**Pull request merged**
