### PR TITLE
Rampboost fix

### PR DESCRIPTION
**Pull request by TotallyMehis**
Fixes the random nature of rampboosts by running a second TryPlayerMove() when ground check is done to ensure velocity reflect.

On a side note, this is my first pull request so I apologize if I messed something up.

### CODE REVIEW

**Comment by RabsRincon** [comment]
Hi TotallyMehis!
Thanks for helping us on the development of the mod :smile: 
I'm going to review your pull request and I'll write again when I finish.

And by the way, you didn't screw anything. Nice job!

One thing I've noticed is that you're modifying virtual functions from a very "base" class. Couldn't this cause problems with their overrides? Did you take care of it?

For the pull request to be merged, when (if (but I'm quite sure it'll be, because it seems you know what you're doing!)) accepted, I'll have to speak with Gocnak before pressing the button, so, sorry about it!

:)

**Comment by RabsRincon** [comment]
Hello again TotallyMehis. Can you check for me if the game crashes for you with this pull please?
I'm unable to launch the game. it crashes on startup

**Comment by TotallyMehis** [comment]
Yes, it crashes for me too now. It played fine previously.

**Comment by RabsRincon** [comment]
Please notify me when you fix the issue, so I can re-test it :)

**Comment by TotallyMehis** [comment]
I think there was a misunderstanding. My original pull request worked fine, with rampboost fix and all. However, after merging with some updates the game started crashing. I re-merged and now everything seems fine.

I also updated the rampboost fix to take into account the surface normal.

**Comment by RabsRincon** [comment]
I tested it and works great :+1:
We're (Well, goc is) currently heavily editing the source files in the so called MOMification process, so I'll have to wait until he finishes (or he gives me green light) to merge it.

**Comment by Gocnak** [comment]
Hey, wonderful work on this commit!

I've tested the code out as well and all is well. You're submitting this at an interesting time, where I am taking up the task of the "MOMification" of the mod, where I'm making momentum-specific classes, such as mom_gamemovement.cpp. 

I've gone ahead and included all of the commits (as of this comment) in the new files. I suggest you look at them to see how I went about doing it, as changing method signatures of virtual methods is not the way to go, as it ruins the overriding property of them.

But other than that, fantastic work. I'll be closing this pull request since we're going to no longer touch gamemovement.cpp. However, I would love to have you caught up with our team's communications! I can invite the email on your GitHub profile to our Slack, where we communicate, if you want. Unless there's some other method of communication you prefer, just let me know!

**Pull request closed without merging**
