### PR TITLE
Add NetBeans project for Linux and make it possible to compile without sudo

### PR DESCRIPTION
**Pull request by chrb22**
Adds a NetBeans project and makes it possible to compile using schroot without sudo on Linux. The instructions to setup both of these are below.

	If project already has been compiled with sudo:
		cd to game/mp/
		run "sudo chown -R <username>:<username> ." where <username> is your username

	Non-sudo setup:
		Replace "groups=sudo" with "groups=<username>" in /etc/schroot/chroot.d/steamrt_scout_i386.conf where <username> is your username
		cd to game/mp/src/
		run "./creategameprojects"
		run "schroot --chroot steamrt_scout_i386 -- make -f games.mak" to compile

	NetBeans Setup (requires steps above, except compiling):
		Install NetBeans (netbeans package)

		Tools->Plugins
			Settings->Check NetBeans 8.2 Plugin Portal
			Available Plugins->Install C/C++

		Tools->Options
			Editor->Formatting
				Language: All Languages
				Category: Tabs and Indents
				Expand Tabs to Spaces: Check
				Number of Spaces per Indent: 4
				Tab Size: 4
				Right Margin: 120
			Editor->On Save
				Language: All Languages
				Reformat: None
				Remove Trailing Whitespace From: Modified Lines Only

		File->Open Project
			Select game/mp/src

		File->Project Properties
			General->Add Source Folder: Select game/mp/src
			Run->Run Directory: <path to MomentumDev> (Server and Client configuration)
			Run->Run Command: <change run parameters to liking> (Server and Client configuration)

		Run->Build Project (F11)
		Debug->Debug Project (F5) (Run->Run Project (F6) doesn't work for some reason)

### Checklist
- [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [x] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

**Comment by bltech** [comment]
Really stoked for the project file! I do wonder why the /bin changes? I have been compiling without sudo for a while now on the current file and didn't have any issues

**Comment by chrb22** [comment]
> Really stoked for the project file! I do wonder why the /bin changes? I have been compiling without sudo for a while now on the current file and didn't have any issues

I didn't work for me without the /bin/ changes, so that's why :)

**Comment by bltech** [comment]
Makes sense, guess it doesn't hurt anyway :)

**Comment by Gocnak** [comment]
Awaiting ubuntu testing

**Pull request merged**
