### PR TITLE
Fizzle furthest sticky instead of first placed (-mapping only for testing)

### LINKED ISSUE #932: Avoid forcing player to reset stickies when failing the pre on a double pre
Requested by bn ( @notbad69 )

**What feature is your improvement idea related to? Please describe.**
When the player messes up the prefire on a double pre without detting, they are forced to reset their stickies (det them and retry entire double pre). This is because the first shot sticky will be fizzled (one in the double).

**Describe the solution you'd like**
Two solutions:

1. Allow only the 3 closest stickies to effect the player and give them a higher sticky cap. 

2. When a sticky is fizzled by shooting a 4th, fizzle the one furthest from the player instead of the first shot. This would fizzle the pre instead of the double when retrying. 

I suggest (2) as it has the added benefit of limiting how many stickies can be placed and generally seems more intuitive to me.

### PR DESCRIPTION
**Pull request by braem**
Closes #932 

Would like some testing first. Perhaps @notbad69 as they requested it (indirectly)? Maybe @TheRealHona if he wants :)

### Checklist
- [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [x] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

**Comment by TheRealHona** [comment]
I'll test this later today or tomorrow

**Comment by braem** [comment]
> I'll test this later today or tomorrow 

Community seems divided about it. Might close the PR, or at least wait to discuss it in the meeting.

**Comment by braem** [comment]
Made a mapping mode only toggle cvar for this code.

**Comment by braem** [comment]
Reached the decision that this issue is not something we should solve.

**Pull request closed without merging**
