### PR TITLE
PBR defaults textures

### LINKED ISSUE #728: PBR default textures
The defaults for basecolor and mrao are no good. The color is much too bright, the roughness is much too shiny, the ambient occlusion makes your material black.

It's easy to solve, just add two VTF files and tell the CPP to use them.

I don't have an alternative solution but like this one's done, already merged into Thexa4's repo even.

I'm too lazy to take screenshots showing the issue.

### PR DESCRIPTION
**Pull request by bonjorno7**
Closes #728 

Just adds default VTFs for basetexture and mraotexture, and tells the CPP to use them.

### Checklist
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

**Comment by Gocnak** [comment]
Can I get a screenshot of these defaults since it's not really code to review?

**Comment by bonjorno7** [comment]
Desktop Screenshot 2020 05 05 - 20 47 11 32
As you can see the materials look like plastic (as opposed to pitch black or blinding white, like the old defaults).

**Comment by bonjorno7** [comment]
Desktop Screenshot 2020 05 05 - 21 00 15 57
And here it is with just a bumpmap.

**Comment by bonjorno7** [comment]
Which uh is after I fixed it cause there's actually an issue with the code that I found just now yikes.

**Comment by bonjorno7** [comment]
Alright it's as good as it's gonna get now but I did it on another branch, gonna close this PR and include it in that one.

**Pull request closed without merging**
