### PR TITLE
Fix for speedo setup not loading properly on hud settings page on launch

### PR DESCRIPTION
**Pull request by braem**
Small bug I noticed with loading/saving speedo setups: when the game is first launched and the hud settings are opened before entering a map, the speedo settings were not being loaded/saved correctly.

This is because the `m_CurrentlyLoadedGamemodeSettings` field in `hud_speedometer_data` is `GAMEMODE_UNKNOWN` on launch.

Fixed by just defaulting to loading/saving surf speedo setup when the gamemode isn't known. Unknown gamemodes use surf settings anyways so this change is in line with that.

### Checklist
- [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [x] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

**Comment by Gocnak** [comment]
Sorta unrelated but actually related: can you bump the speedometer Y pos up a bit? I get some overlap with all of the labels enabled @ 2K+: 
image

**Comment by braem** [comment]
> Sorta unrelated but actually related: can you bump the speedometer Y pos up a bit? I get some overlap with all of the labels enabled @ 2K+:

I wasn't worrying so much about overlap if all of them are enabled. If we did might have to worry more about the sticky chargemeter. Would have to be near center to fit all the labels there.

**Comment by Gocnak** [comment]
>If we did might have to worry more about the sticky chargemeter. 

Well, it's important to consider that some game modes just won't be using some speedometers. SJ won't have surf board / leave speed, for example, which is causing what you see (zone exit speed being all the way down over the zone info label) in my screenshot. 

The main thing to consider with UI is, if we offer people the option, never assume they won't use it. UI should try to look good in every case, even the worst. So it may be beneficial to activate all the speedometers allowed for the different game modes and make sure they make sense and are readable. In this case I honestly think just bumping up quite some of the Y may do the trick, it is going to be closer to the speedometer but that's alright. Could try just moving it up half the distance between the center dot of the crosshair in my image and the top of the first value label.

**Comment by braem** [comment]
Added localization for unknown gamemodes and changed it from `#MOM_NotApplicable` to `#MOM_GameType_Unknown`. Had  to change your loading tips res file as that was using `#MOM_NotApplicable`.
Added a speedo setup for this unknown gamemode, tweaking the hud settings page to show it.

As for the position of the speedometer, I moved it up. This is what it looks like with all the speedos useful for SJ (everything but last jump vel & ramp ones):
image
And for surf (everything but explosive speed):
image

Settings page:
image

Perhaps we should disable some of the speedo type options depending on the gamemode to prevent overlap in the HUD. Just from the hud settings page so users can switch them on via editing the cfg file still. Could throw that in the VDF file or just hardcode it. 
Also might be nice to have a y offset for each of the gamemodes in the VDF file.

Would be for a separate PR though as these don't really relate to this fix.

**Pull request merged**
