### PR TITLE
Offline release

### PR DESCRIPTION
**Pull request by lvaness**
As discussed,

I gutted all Momentum API calls, disabled hud elements requiring online access and added a bit of information to reduce confusion.
These changes (apart from the API calls) are pretty superficial and not strictly enforced (you can still change online settings via console for example or modify res files) but clear enough that it's obvious it's deliberate. I disabled all the elements I could instead of removing them to show off what is going to be accessible in the future.

I didn't localize the strings in question as I doubt anyone is going to bother translating them anyways but if that's wanted I can add them properly.

I also turned on mapping mode by default since people will have to create most zones themselves anyways and there is no online submission to worry about.

I tested disabling the Steam API completely after TF2/CSS get mounted but that just resulted in a lot of crashes so I left that in (I hope Valve can excuse the few calls that still exist).

Screenshot_20201208_132421
Screenshot_20201208_133209
Screenshot_20201208_135248
Screenshot_20201208_151747
Screenshot_20201208_163956

~What is missing: final 0.8.7 PR and version change in code (I wanted to avoid the inevitable merge conflict that would arise) and a separate branch to merge into, as having this on develop doesn't make much sense for archiving reasons IMO.~

### Checklist
- [X] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
- [X] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [X] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [X] If I have added or modified any visual assets (models, materials, panels, effects, etc), I have taken screenshots / videos of them and attached them to this PR directly (screenshots uploaded through github, videos uploaded to youtube and linked)
- [X] If I have modified any console command, console variable, or momentum entity, I have opened an issue (or a PR) for it in the [Momentum Mod documentation repository](https://github.com/momentum-mod/docs)
- [X] My commits are relatively small and scoped to the best of my ability
- [X] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [X] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

**Comment by bltech** [comment]
Oh and should I maybe (re)link trigger_momentum_teleport to CTriggerTeleport for this? Do the Momentum map releases going around from various FastDL servers have trigger_teleports or the momentum variant?

**Comment by Gocnak** [comment]
Don't worry about the teleport trigger, it keeps it forwards compatible for as long as possible.

As for changelog and version bump, I will be committing that on develop today, and you can rebase onto it then. I'll also create the branch to merge this into, maybe even making it the default visible on GitHub.

**Comment by Gocnak** [comment]
Okay you should be able to rebase onto upstream/public/0.8.7, and mark this ready for review, when ready.

**Comment by bltech** [comment]
Does this need documentation on the docs site? Maybe the "Building the game" section should be replaced with instructions to check out the build? Or another page for that with the building instructions being deprecated and having a disclaimer.

**Comment by Gocnak** [comment]
Yes. It would be wise to have a giant info banner at the top of the build guide with the link to the 0.8.7 build, but still allow those to compile the game following the instructions if they desire.

**Review by Gocnak — APPROVED** [review]

**Pull request merged**
