### PR TITLE
Changed GameUI video settings to apply instantly

### PR DESCRIPTION
**Pull request by braem**
This is a branch off PR #702 to use `CvarTextEntry` number format override functionality.
Now that the momentum settings changed to apply instantly, I'm attempting to make the same changes to the GameUI code  - Issue #708 

There are 3 main changes in this PR:

1. Allowed the comboboxes on the main video settings page to apply instantly.
2. Converted the gamma dialog to the instant applying `CvarSlider` & `CvarTextEntry`.
    - Had to add a missing res file that was being referenced: `optionssubvideogammadlg.res`. It seems many source related repos have this resource file, and that they are almost all identical. May have gotten lost somewheres.
    - Moved class definition to the header file.
3. Changed the advanced video settings dialog to apply on it's OK button rather than waiting for the main video settings dialog's apply button to be pressed.
    - FOV slider wasn't being reset properly here. Changed that.
    - Moved class definition to the header file.
    - Moved `ConVarRef` calls to the constructor. Even though this shouldn't matter too much as the dialog is being instantiated on button press. Might be changed later though.

### Checklist
- [x] If there is a localization token change, I have updated the `momentum_english_ref.res` file with the changes, ran `tokenizer.py` to generate an up-to-date localization file, and have committed both the `.res` file changes and the new localization `.txt` file
- [x] If I introduced new h/cpp files, I have added them to the appropriate project's VPC file (`server_momentum.vpc` / `client_momentum.vpc` / etc)
- [x] My commits are relatively small and scoped to the best of my ability
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review

### CODE REVIEW

**Comment by Gocnak** [comment]
I feel like this is where we start to be careful. Instantly applying video changes isn't always the best thing to do as it could be a destructive change ( e.g. fat-fingering the wrong resolution causing the game to be too big).

It's unfortunate because it's the only panel that needs to behave like this, the rest of the panels are fine with instant applying. Similarly, it's only resolution changing that is detrimental here, unless, have you tested this in-game? Does it cause stuttering when changing things like AA, reflections, etc?

**Comment by braem** [comment]
> it's only resolution changing that is detrimental here, unless, have you tested this in-game? Does it cause stuttering when changing things like AA, reflections, etc?

The advanced options do not apply instantly, rather when OK is pressed on the advanced modal dialog. Before you would have to click OK on the modal and then OK/Apply on the main dialog for changes to take effect. Just planning on removing the OK/Cancel/Apply on the main dialog not on the modals. This takes away being able to set all advanced options and the resolution all at once, but that seems minor.

The gamma modal already had code that instantly updated the gamma (so as to preview). This has the same functionality. Cancel will revert the setting and OK will keep it.

This leaves just 2 comboboxes on the main video dialog: screen resolution and aspect ratio. The aspect ratio combobox only updates what items are in the resolution combobox. So the only real worry is the screen resolution change. I called the same function that is called upon pressing OK/Apply so no issues should arise that aren't already present.

I tested the resolution changes in game and it was crashing the game _sometimes_. An exception is thrown in `dynamicrendertargets.cpp`. Seemed weird so I tested this on current develop and the same thing happens (after changing resolution then clicking OK/Apply). This does not occur in 0.8.4. I tested with different combinations of `+developer` and `-mapping` and the result was the same.

Also, I found that changing the shader quality froze the game in 0.8.4, develop, this branch, etc. Either it's stuck or takes a very long time to reload, not sure. 

These things can be remedied by modifying the `RequiresRestart()` function, so that retry is called. Shader quality & resolution changes work fine when not in a map.

**Comment by Gocnak** [comment]
Needs rebasing. Make sure to do an interactive rebase and to **delete the lines (commits) that were overwritten by your PR at #702**, since this branch is out of date with it and will try to "revive" those commits (since git doesn't know it was originally in your old PR; you overwrote them with a force push).

> This takes away being able to set all advanced options and the resolution all at once, but that seems minor.

The options panel redesign UX is currently doing will tackle that, don't worry.

> I tested the resolution changes in game and it was crashing the game sometimes. An exception is thrown in dynamicrendertargets.cpp

Yeah I've seen this happen before too, not good. We've had repeat offenders with crashing while changing resolution. Usually to find the cause it's to git bisect back to a good commit and play a very lengthy game of "will this compile be the one that works finally?" 

> These things can be remedied by modifying the RequiresRestart() function, so that retry is called. Shader quality & resolution changes work fine when not in a map.

Also not good, they *should* work while in game, so something changed. Needs further debugging, can be done outside this branch.

**Comment by braem** [comment]
> Needs rebasing. Make sure to do an interactive rebase and to **delete the lines (commits) that were overwritten by your PR at #702**, since this branch is out of date with it and will try to "revive" those commits (since git doesn't know it was originally in your old PR; you overwrote them with a force push).

Done :) 

> The options panel redesign UX is currently doing will tackle that, don't worry.

😮 Cant wait to see what that's gunna look like!

**Pull request merged**
